import type { Metadata } from 'next'
import React, { ReactNode } from 'react'

import { Navigation } from '@/components'

import { subNavigation } from '@/configuration/navigation'

export const metadata: Metadata = {
  title: 'Api data Provider',
  description: 'Generated by create next app',
}

export default function ApiDataRootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <>
      <h2>State Managements</h2>
      <Navigation tabs={subNavigation.stateManagement} navType={'secondary'} />
      {children}
    </>
  )
}
