import './globals.css'
import './styles/main.scss'
import type { Metadata } from 'next'
import React, { ReactNode } from 'react'
import { roboto } from '@/app/fonts'
import { Breadcrumb, Navigation } from '@/components'
import QueryProvider from '@/api-providers/tanstack/provider'
import { navPrimary } from '@/configuration'
import { ApolloClientProvider } from '@/api-providers/graphQL-apollo/apolloProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <ApolloClientProvider>
      <QueryProvider>
        <html lang="en" className={roboto.className}>
          <body>
            <div className="display-grid display-grid-temp-nav-primary">
              <Navigation tabs={navPrimary} />
              <main>
                <Breadcrumb />
                {children}
              </main>
            </div>
          </body>
        </html>
      </QueryProvider>
    </ApolloClientProvider>
  )
}
