import './globals.css'
import type { Metadata } from 'next'
import React, { ReactNode } from 'react'
import { geistMono, geistSans } from '@/app/fonts'
import { Navigation } from '@/components'
import QueryProvider from '@/api-providers/tanstack/provider'
import { navPrimary } from '@/configuration/navigation'
import { ApolloClientProvider } from '@/api-providers/graphQL-apollo/apolloProvider'
import { ApolloProvider } from '@apollo/client/react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <ApolloClientProvider>
      <QueryProvider>
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
          <body style={{ margin: '3rem' }}>
            <Navigation tabs={navPrimary} />
            <hr />

            {children}
          </body>
        </html>
      </QueryProvider>
    </ApolloClientProvider>
  )
}
